cls
@echo off
chcp 1251 >nul
title ”даление пунктов KMPlayer из контекстного меню

echo ¬ыполн€етс€ удаление пунктов "Play in KMP" из контекстного меню:
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3g2\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gp\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gp2\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gpp\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.a52\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aac\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ac3\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aif\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aifc\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aiff\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.alac\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.amr\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.amv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ape\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.asf\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ass\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.asx\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.au\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.avi\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.avs\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.cda\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.dat\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.divx\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.dts\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.evo\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.f4v\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flac\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flc\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.fli\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.gvi\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.hdmov\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.idx\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ifo\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.k3g\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.kpl\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m1a\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m1v\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2a\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2t\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2ts\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2v\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m3u\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m3u8\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4a\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4b\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4p\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4v\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mid\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mk3d\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mka\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mkv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mov\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp+\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp1\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp2\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp2v\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp3\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp4\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpa\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpc\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpe\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpeg\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpg\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpp\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpv2\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mqv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mts\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mtv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.nsa\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.nsv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ofr\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ofs\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.oga\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogg\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.pls\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.qt\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ra\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ram\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmj\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rms\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmvb\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rt\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.skm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.smi\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.snd\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.spx\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.srt\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ssa\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.sub\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.swf\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tp\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tpr\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ts\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tta\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.vob\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.vp6\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wav\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wave\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wax\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.webm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wm\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wma\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmp\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmv\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmx\shell\play" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wv\shell\play" /f
echo.

echo ¬ыполн€етс€ удаление пунктов "Enqueue in KMP" из контекстного меню:
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3g2\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gp\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gp2\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.3gpp\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.a52\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aac\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ac3\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aif\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aifc\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.aiff\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.alac\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.amr\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.amv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ape\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.asf\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ass\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.asx\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.au\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.avi\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.avs\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.cda\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.dat\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.divx\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.dts\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.evo\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.f4v\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flac\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flc\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.fli\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.flv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.gvi\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.hdmov\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.idx\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ifo\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.k3g\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.kpl\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m1a\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m1v\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2a\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2t\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2ts\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m2v\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m3u\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m3u8\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4a\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4b\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4p\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.m4v\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mid\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mk3d\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mka\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mkv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mov\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp+\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp1\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp2\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp2v\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp3\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mp4\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpa\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpc\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpe\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpeg\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpg\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpp\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mpv2\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mqv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mts\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.mtv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.nsa\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.nsv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ofr\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ofs\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.oga\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogg\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ogv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.pls\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.qt\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ra\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ram\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmj\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rms\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rmvb\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rt\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.rv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.skm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.smi\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.snd\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.spx\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.srt\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ssa\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.sub\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.swf\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tp\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tpr\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.ts\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.tta\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.vob\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.vp6\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wav\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wave\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wax\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.webm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wm\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wma\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmp\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmv\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wmx\shell\Enqueue" /f
reg delete "HKEY_CLASSES_ROOT\KMPlayer64.wv\shell\Enqueue" /f
echo.

pause